### ISSUE TITLE
when k is > 1 , the Recall is lower than it is for the C version of fastText

### ISSUE THREAD

**Issue by lefromage** [ivanhk/fastText_java#10]
when k = 3 , R@3 from the fastText java version is 0.05 lower than R@3 for fastText C version.
this was done on the yelp_review_full dataset - Thanks

FastText in C:
     R@1: 0.638 for k=1
     R@3: 0.975 for k=3
FastText in Java:
     R@1: 0.638 for k=1
     R@3: 0.922 for k=3

when k=1, it is the same which is good.

**Comment by lefromage** [comment]
in the case, of a dataset with many classes (> 100) the difference in Recall R@1 and R@3 
between k = 1 and k =3 is much bigger

**Comment by lefromage** [comment]
| Fasttext Java |  |  | FastText C | 
k | R@k |     sum R@k |  | R@k |     sum R@k
-------------------------------------------------------------------- |  |  |  |  | 
1 | 73.10% | 73.10% |  | 72.00% | 72.00%
2 | 4.30% | 77.40% |  | 9.40% | 81.30%
3 | 0.70% | 78.10% |  | 4.00% | 85.30%
4 | 0.20% | 78.20% |  | 2.20% | 87.50%
5 | 0.00% | 78.30% |  | 1.30% | 88.80%
6 | 0.00% | 78.30% |  | 1.00% | 89.80%
7 | 0.00% | 78.30% |  | 0.60% | 90.50%
8 | 0.00% | 78.30% |  | 0.60% | 91.00%
9 | 0.00% | 78.30% |  | 0.40% | 91.40%
10 | 0.00% | 78.30% |  | 0.30% | 91.70%

**Comment by ivanhk** [comment]
The cause should be the different  implementation of java sort and cpp sort. 
Should not be a big issue for now. 
The solution is to re-implement the sort algorithm in java.

**Comment by lefromage** [comment]
I think the problem may be that too many of the scores are the same in Java somehow.
in C the score are much more different so they get sorted better.
There's probably nothing wrong with the sort algorithm, but maybe a bug in the probability calculation. this may happen more when there is large number of classes in the case of 1000s or even 10,000s classes.
Thanks

**Comment by lefromage** [comment]
the problem is more significant on yelp_review_full dataset

before FIX
R@1: 0.638
R@3: 0.922

after FIX:
R@1: 0.638
R@3: 0.975

which is the same as the result for fastText in C

**Comment by ivanhk** [comment]
thanks
