### ISSUE TITLE
can a model created by fastText C be used in FastText Java and vice versa ?

### ISSUE THREAD

**Issue by lefromage** [ivanhk/fastText_java#11]
is the compatibility of the bin models between C and Java planned or even feasible ?

The models generated seem to be readable in both C and Java fastText.

The model.bin generated from fastText C gives much lower Recall  when used with fastText Java.

Thanks

**Comment by ivanhk** [comment]
The model generated from Java and cpp is compatible. 
I just tested, using Java model in cpp fasttext, give almost same result as cpp model. 

The lower recall in fastText Java using cpp model, due to different sort algorithm in java/cpp. The order is different if the score of item is the same.
