### ISSUE TITLE
hierarchical softmax is giving a lot of identical probabilities

### ISSUE THREAD

**Issue by lefromage** [ivanhk/fastText_java#13]
this is for the the first 3 lines of the test dataset ag_news , after training on ag_news dataset:

__label__2 , federer back in open #39 s fourth round with masterful performance , for most tennis players , having about the same number of clean winners as unforced errors translates into a pretty good performance . 
__label__1 , negotiations for hostages in afghanistan fall short , militants holding hostage three foreign un workers in afghanistan said they negotiated yesterday with afghan government and un officials in southern afghanistan but that the meeting ended without results . 
__label__1 , europe serbia calls on un to annul appointment of kosovo pm , he ( haradinaj ) is a war crimes suspect , and serbian authorities will face numerous difficulties . . . with such a person , 
kostunica said . 

default loss:
__label__2 0.998047__label__4 0.000000__label__1 0.000000__label__3 0.000000
__label__1 1.000000__label__2 0.000000__label__4 0.000000__label__3 0.000000
__label__1 0.998047__label__2 0.000000__label__4 0.000000__label__3 0.000000
R@1: 0.925

Hierarchical softmax: -loss hs
__label__3 0.250000__label__1 0.250000__label__4 0.250000__label__2 0.250000
__label__3 0.250000__label__1 0.250000__label__4 0.250000__label__2 0.250000
__label__3 0.250000__label__1 0.250000__label__4 0.250000__label__2 0.250000
R@1: 0.918

**Comment by lefromage** [comment]
command to reproduce

  head -3 "${DATADIR}/${DATASET[i]}.test"
  head -3 "${DATADIR}/${DATASET[i]}.test" | java -jar ${JAR} predict-prob "${RESULTDIR}/${DATASET[i]}_hs.bin" - 5

**Comment by lefromage** [comment]
in fasttext C , there is no such issue:

default loss: [ns]
__label__2 0.998047 __label__3 1.95313e-08 __label__1 1.95313e-08 __label__4 1.95313e-08
__label__1 1 __label__3 1.95313e-08 __label__2 1.95313e-08 __label__4 1.95313e-08
__label__1 0.998047 __label__3 1.95313e-08 __label__2 1.95313e-08 __label__4 1.95313e-08
R@1: 0.924

Hierarchical softmax: -loss hs
__label__2 0.982452 __label__4 0.0091858 __label__1 0.00445939 __label__3 1.92261e-08
__label__1 1 __label__4 1.95313e-08 __label__3 1.90354e-08 __label__2 4.57764e-10
__label__1 0.990234 __label__4 0.00781252 __label__3 1.7128e-08 __label__2 2.36511e-09
R@1: 0.92

**Comment by lefromage** [comment]
I chose to make the issue as easily to reproduce as possible.
The ag_news dataset is the smallest and available here in case you need it:
https://drive.google.com/drive/folders/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M

**Comment by ivanhk** [comment]
thx, i will look at it later on.

**Comment by lefromage** [comment]
correction , the PR is for issue #10
