### ISSUE TITLE
Bug in Dictionary.java

### ISSUE THREAD

**Issue by gembin** [ivanhk/fastText_java#14]
* I think this line is wrong, the **count** will **NOT** changed in the original `List<String> words_`
https://github.com/ivanhk/fastText_java/blob/master/src/main/java/fasttext/Dictionary.java#L123

* Per my understanding, this line should be  e.type = w.**startsWith**(args_.label) ? entry_type.label : entry_type.word
https://github.com/ivanhk/fastText_java/blob/master/src/main/java/fasttext/Dictionary.java#L119

**Comment by ivanhk** [comment]
this method will only called by Dictionary.readFromFile to initialize the dict in training.  Use Dictionary.toString() method to output the content of dict object. I can't see the bug in count.

**Comment by ivanhk** [comment]
Yup, it should be startsWith, not contains.

**Comment by lefromage** [comment]
1) it seems to be  working 
this test could be added to TestDictionary.java
https://github.com/ivanhk/fastText_java/blob/8514eb8e22f93242abeda5b6988284608c7282a7/src/test/java/fasttext/TestDictionary.java

	@Test
	public void testAdd() {
		dictionary.add(",");
		dictionary.add("is");
		dictionary.add("is");
        String w = "</s>";
        dictionary.add(w);
		dictionary.add(w);
		dictionary.add(w);
        long h = dictionary.find(w);
        Map<Long, Integer> word2int = dictionary.getWord2int();
        Integer index = word2int.get(h);
        assertEquals( 3, dictionary.getWords().get(index).count);
        assertEquals( 2, dictionary.getWords().get(word2int.get(dictionary.find("is"))).count);
        assertEquals( 1, dictionary.getWords().get(word2int.get(dictionary.find(","))).count);
	}

2) I would agree to using startsWith is probably more correct than contains

**Comment by ivanhk** [comment]
added, and welcome pull request.

**Comment by gembin** [comment]
Oh, yep, my mistake,  count is correct
