### ISSUE TITLE
breaking changes introduced in c1296469db43a2153e2a074a6733c8adc03e9480

### ISSUE THREAD

**Issue by lefromage** [ivanhk/fastText_java#15]
changes introduced in "MappedByteBufferLineReader add support for inputstream"
caused less lines to be displayed or processed in predict-prob and test: 
- for predict-prob: using head -3 data/ag_news.test : 1 line is printed instead of 3 
- for test: 150 lines instead of 7600 processed

before:

**using predict-prob , fed with   head -3 data/ag_news.test**
__label__2 0.998047__label__4 0.000000__label__1 0.000000__label__3 0.000000
__label__1 1.000000__label__2 0.000000__label__4 0.000000__label__3 0.000000
__label__1 0.998047__label__2 0.000000__label__4 0.000000__label__3 0.000000

**using test on full file: data/ag_news.test**
P@1: 0.926
R@1: 0.926
Number of examples: **7600

after:

**using predict-prob , fed with   head -3 data/ag_news.test (only shows 1 line)**
__label__2 0.998047__label__4 0.000000__label__1 0.000000__label__3 0.000000

**using test on full file: data/ag_news.test (only processes 150 lines)**
P@1: 0.920
R@1: 0.920
Number of examples: 150

**Comment by ivanhk** [comment]
Thanks, 
changed to use BufferedLineReader as default, although MappedByteBufferLineReader is 40%-50% faster than BufferedLineReader in reading text file. But MappedByteBufferLineReader can't open huge dataset.

I will fix the MappedByteBufferLineReader InputStream bug later on.

**Comment by lefromage** [comment]
Thanks, 
the code is now working again.
