### ISSUE TITLE
when I use the code as an online service, it turns out it's not thread safe, is it ?

### ISSUE THREAD

**Issue by zhouxinhit** [ivanhk/fastText_java#25]

**Comment by ivanhk** [comment]
2 predict api in FastText.java, first one is thread-safe, second one is thread unsafe.
public List<Pair<Float, String>> predict(String[] lineTokens, int k)
public void predict(String[] lineTokens, int k, List<Pair<Float, String>> predictions) throws IOException

**Comment by zhouxinhit** [comment]
thank you
