### ISSUE TITLE
Is Fastext java working?

### ISSUE THREAD

**Issue by gembin** [ivanhk/fastText_java#6]
I used fasttext binary (cpp version) to train the data, and predict-prob for the result.
and then use fastext_java to load the trained model, but predict-prob for result, they got completely different results.

e.g. the score
cpp: 0.999....   (perfectly matches the actual result)
java: -1.67...

**Comment by ivanhk** [comment]
oops... just update the code, haven't test code yet. i try to fix it this week

**Comment by ivanhk** [comment]
fixed, please check it out

**Comment by gembin** [comment]
`predict-prob` with k=`5`, it's much better,  and is this result normal?

java
```
__label__meeting 0.994141__label__HAM 0.003906__label__SPAM 0.000000__label__HAPPY 0.000000
__label__meeting 0.998047__label__SPAM 0.000000__label__HAM 0.000000__label__HAPPY 0.000000
__label__HAPPY 0.757813__label__HAM 0.115234__label__SPAM 0.082031__label__meeting 0.041016
```
cpp
```
__label__meeting 0.982422 __label__HAM 0.0117188 __label__HAPPY 0.00195314 __label__SPAM 0.00195314
__label__meeting 0.994141 __label__HAM 0.00390627 __label__HAPPY 1.95313e-08 __label__SPAM 1.95313e-08
__label__HAPPY 0.757813 __label__HAM 0.115234 __label__SPAM 0.0820313 __label__meeting 0.0410156
```

**Comment by gembin** [comment]
I tried supervised training, the generated model is much bigger than cpp's one, `java(4MB) vs cpp(2KB)`.

java
```java
FastText fasttext = new FastText();
Args args = new Args();
args.bucket = 100000;
args.lr = 0.5;
args.dim = 10;
args.epoch = 20;
args.input = "/path/to/data/my/train.txt"; 
args.output = "/path/to/data/my/model";
args.model = model_name.sup;
fasttext.train(args);
```

cpp
```shell
./fasttext supervised -input /path/to/data/my/train.txt -output /path/to/data/my/model -dim 10 -lr 0.5 -epoch 20 -bucket 100000
```

and tried to use fastext_java to`predict-prob` with `k=5` the result is bad. It seem the training is not working.

```
__label__meeting 0.250000__label__SPAM 0.250000__label__HAM 0.250000__label__HAPPY 0.250000
__label__meeting 0.250000__label__SPAM 0.250000__label__HAM 0.250000__label__HAPPY 0.250000
n/a
```

**Comment by ivanhk** [comment]
let see if i can found the problems

**Comment by ivanhk** [comment]
The training should be ok now. Almost the same as cpp.
The result "__label__SPAM 0.000000__label__HAPPY 0.000000" is normal, the order is different because the implementation of cpp std::sort() and Java Collections.sort() is different.

btw, i am going to re-implement the io parts. Java IO package is too slow compare to cpp io.

**Comment by gembin** [comment]
Nice job!! Thanks!
I suggest to get rid of all the dependencies, guava, math3 and fastutil, just copy the java sources that are used?

And also remove cli?  i think it should be more common to use this as an library rather than a cli tool in java.  WDYT?

**Comment by gembin** [comment]
btw, the generate model is still much bigger in size, ` java(4MB) vs cpp(2KB)`.

**Comment by gembin** [comment]
One more problem, the training output is not correct.

should be:
```
Read 0M words
Number of words:  23
Number of labels: 3
```
but was:
```
Read 0M words
Number of words:  1
Number of labels: 3
```

**Comment by ivanhk** [comment]
can you provide the input data file, so i can reproduce the problem. I tested with  "dbpedia.train" with same result as cpp.

**Comment by gembin** [comment]
train.txt
```
__label__SPAM  buy our products
__label__HAM  Please send me the last business forecast
__label__SPAM  buy viagra
__label__HAM  important meeting at 10:00AM
__label__PROD_A  __label__HAPPY I'm very happy with product A
```
should be
```
Number of words:  22
Number of labels: 4
```

**Comment by ivanhk** [comment]
the result is correct, when you use minCount 1, the default minCount is 5.

**Comment by gembin** [comment]
ah, ok, thanks!

**Comment by gembin** [comment]
Some comments, : -)
* `java.util.Vector` is considered obsolete, it's recommended to use `ArrayList` instead, and use `CopyOnWriteArrayList` or `Collections.synchronizedList(new ArrayList())` for thread safety if needed.
* Use `ThreadLocalRandom` instead of `Random`? But it requires java 1.7+
* [Utils.java Line 67](https://github.com/ivanhk/fastText_java/blob/master/src/main/java/fasttext/Utils.java#L67) will throw ex, `e.g. lower=1, upper=1`

**Comment by ivanhk** [comment]
thanks for the suggestion.
