### ISSUE TITLE
when testing need to give parameter k != 1

### ISSUE THREAD

**Issue by lefromage** [ivanhk/fastText_java#8]
usage: java -jar fasttext.jar test <model> <test-data> [<k>]
does not seem to allow me to have a number in the place of the 3rd parameter k

for ex: 
time java -Xmx5g -jar ${JAR} test model_last1month_solr_dim_50_NUM.bin last1month_solr_test.fasttext_NUM.tsv 
P@1: 0.001
R@1: 0.001
Number of examples: 256887

time java -Xmx5g -jar ${JAR} test model_last1month_solr_dim_50_NUM.bin last1month_solr_test.fasttext_NUM.tsv 2
usage: java -jar fasttext.jar test <model> <test-data> [<k>]

  <model>      model filename
  <test-data>  test data filename (if -, read from stdin)
  <k>          (optional; 1 by default) predict top k labels

**Comment by ivanhk** [comment]
fixed, thanks
