### ISSUE TITLE
FAIL Test line: warns no labels [] even though test data line has label

### ISSUE THREAD

**Issue by lefromage** [ivanhk/fastText_java#9]
FAIL Test line: __label__3~This~That~Other_Things	^rot rota otar tary ary* ry*d y*da *dam damp ampe mper pers ers$

labels: [] line: [3664, 2327, 2693, 1611, 1114, 4042, 9464, 4485, 3660, 2205, 470, 668, 1, 0, 3427668, 4083919, 7173710, 9927554, 8507374, 3841280, 9231603, 8560027, 9360036, 9344656, 3336762, 9208959, 1247582, 4476722, 5434238, 1019056, 2995203, 7259211, 1030836, 8180544, 3990474, 4495805, 3604703, 6399885, 7479127, 6213843, 7518836, 4053238, 4837757, 1499059, 5970475, 9318072, 6639958, 2236368, 7473448, 3678110, 4863645, 6985225, 9743550, 9902926, 1001796, 7595675, 2081031, 10276757, 2711901, 2066178, 4030576, 6364507, 5762845, 5945049, 6051986, 9218516, 424083, 9532596, 1317814, 9030589, 4673011, 602475, 5271160, 2854934, 4883450, 8386200, 4770963, 4670085, 1485137, 9855418, 3947788, 682080, 6663467, 7621773, 3834281, 2622466, 1568420, 4197358, 6520670, 8582132, 7988779, 1033143, 6085362, 9359120, 2313375, 2664179, 3889787, 8191016, 4558374, 1860802, 3773668, 6341672]

it only happens for 10 lines out of 250,000 , so is not a big issue, but could be a symptom of something else going on.

**Comment by lefromage** [comment]
I realized that github is interpreting the ~ as a strike though (ex:  ~through) 
it is not something weird in the data . the data is just text.

**Comment by ivanhk** [comment]
it just a debug info, either labels or line couldn't retrieve. May be it is confusing, I will remove it.
